import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 16
offset = { x = 0, y = 4 }
