import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
startup_mode = "Fullscreen"
padding = { x = 10, y = 10 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 16
offset = { x = 0, y = 4 }
